version: '3.1'
services:
  redmine:
    build: .
    container_name: redmine
    ports:
      - 8081:3000
#    environment: 
#      - RAILS_ENV="production bundle exec rake redmine:plugins:migrate NAME=redmine_dmsf"